ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER user IDENTIFIED by "passw0rd";
GRANT CONNECT TO user;
GRANT CREATE SESSION TO user;
ALTER USER user PROFILE DEFAULT;
ALTER USER user QUOTA UNLIMITED ON SYSTEM;
GRANT ALL PRIVILEGES TO user;